DI: diagnostic and quick fix for final/abstract injectable methods
eclipse/lsp4jakarta pull request #202
Opened 2021-11-01 05:50 UTC by himanshuc71

Should close #168
Diagnostic for abstract/final method with @Inject
Quick fix to either remove @Inject annotation or the modifier(s)
Integration tests to be added in a later patch

2021-11-03 23:01 UTC, kathrynkodama approved these changes
Other than the minor formatting comment this looks good to me, @himanshuc71 lets add the integration tests as soon as possible

2021-11-04 14:35 UTC, kathrynkodama requested changes
Add check for static methods, see https://github.com/eclipse/lsp4jakarta/issues/168#issuecomment-960416204

2021-11-11 22:24 UTC, himanshuc71 commented on jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/di/DependencyInjectionDiagnosticsCollector.java
> +	            IMethod[] allMethods = type.getMethods();
fixed

2021-11-11 22:27 UTC, himanshuc71 commented
@kathrynkodama, updated the implementation along with the spec. Should be good now. Integration tests coming in another PR.

2021-11-11 22:27 UTC, himanshuc71 commented
> Add check for static methods, see [#168 (comment)](https://github.com/eclipse/lsp4jakarta/issues/168#issuecomment-960416204)

should be good now.

2021-11-12 19:47 UTC, kathrynkodama approved these changes

2021-11-12 19:47 UTC, kathrynkodama commented on jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/di/DependencyInjectionDiagnosticsCollector.java
> + * <li>Diagnostic 3: @Inject methods cannot be abstract.</li>
Should this description be updated to include that methods cannot be generic or static?

2021-11-12 21:12 UTC, merged